export const LOGIN = 'LOGIN';
export const SIGNOUT = 'SIGNOUT';
export const UPDATEPROFILE = 'UPDATEPROFILE';
export const UPDATECATEGORIES = 'UPDATECATEGORIES';
export const UPDATECARTCOUNT = 'UPDATECARTCOUNT';
export const UPDATEWISHIDS = 'UPDATEWISHIDS';
